### ISSUE TITLE
PostgreSQL - LIMIT #,# syntax is not supported

### ISSUE THREAD

**Issue by dwelch2344** [nurkiewicz/spring-data-jdbc-repository#25]
Very interested in the project, but it looks like your limit / offset syntax for postgres is invalid. Recommended solution is to use `OFFSET X LIMIT Y` instead.

Happy to dig in and submit a PR, if it's worth it. Just discovered the project though, so not sure if there's a per-database strategy I need to be aware of... 

```
Caused by: org.postgresql.util.PSQLException: ERROR: LIMIT #,# syntax is not supported
  Hint: Use separate LIMIT and OFFSET clauses.
  Position: 32
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:406)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:286)
	at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:454)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:404)
	... 17 more
```

**Comment by dwelch2344** [comment]
Ah, just finished fishing through the code and realized I have to explicitly set the generator for Postgres. 

It looks like you try to delegate loading it from the BeanFactory, but since you initialize it via `private SqlGenerator sqlGenerator = new SqlGenerator()`  the following will never delegate / look it up: 

```
       @Override
	public void afterPropertiesSet() throws Exception {
		obtainJdbcTemplate();
		if (sqlGenerator == null) {
			obtainSqlGenerator();
		}
	}
```
